default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ticket_flow_development
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  <<: *default
  database: ticket_flow_test
  username: postgres
  password: password
  host: localhost
  port: 5432

production:
  <<: *default
  database: ticket_flow_production
  username: app_user
  password: app_password
  host: localhost
  pool: 5

cable:
  <<: *default
  database: ticket_flow_cable
  username: app_user
  password: app_password
  host: localhost
  pool: 5

cache:
  <<: *default
  database: ticket_flow_cache
  username: app_user
  password: app_password
  host: localhost
  pool: 5

queue:
  <<: *default
  database: ticket_flow_queue
  username: app_user
  password: app_password
  host: localhost
  pool: 5
