default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: ticket_flow_development

test:
  <<: *default
  database: ticket_flow_test

production:
  primary: &primary_production
    <<: *default
    database: ticket_flow_production
    username: ticket_flow
    password: <%= ENV["TICKET_FLOW_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: ticket_flow_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: ticket_flow_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: ticket_flow_production_cable
    migrations_paths: db/cable_migrate
